# GitHub Sponsors
github: CrowbarAutomations/Algorithms
# The funding target is set to the repository "CrowbarAutomations/Algorithms" on GitHub itself

# Patreon
patreon: crowbarautomations
# The funding target is set to the Patreon page of "crowbarautomations"

# Open Collective
open_collective: crowbarautomations
# The funding target is set to the Open Collective page of "crowbarautomations"

# Ko-fi
ko_fi: crowbarautomations
# The funding target is set to the Ko-fi page of "crowbarautomations"
